"""Add module_build monthly_data breakdown_event monthly_kpi

Revision ID: be3a9a52793c
Revises: ff1eafd837be
Create Date: 2026-04-06 01:59:10.059955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3a9a52793c'
down_revision: Union[str, None] = 'ff1eafd837be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('rated_power_wp', sa.Float(), nullable=False),
    sa.Column('degradation_rate_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_builds_id'), 'module_builds', ['id'], unique=False)
    op.create_table('monthly_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('irradiation_kwh_m2', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('tariff_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_data_id'), 'monthly_data', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_data_project_id'), 'monthly_data', ['project_id'], unique=False)
    op.create_table('monthly_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_yield_kwh', sa.Float(), nullable=True),
    sa.Column('pr_percentage', sa.Float(), nullable=True),
    sa.Column('cuf_percentage', sa.Float(), nullable=True),
    sa.Column('target_p50_kwh', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('irradiation_kwh_m2', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_kpis_id'), 'monthly_kpis', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_kpis_project_id'), 'monthly_kpis', ['project_id'], unique=False)
    op.create_table('breakdown_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inverter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loss_kwh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inverter_id'], ['inverters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakdown_events_id'), 'breakdown_events', ['id'], unique=False)
    op.create_index(op.f('ix_breakdown_events_inverter_id'), 'breakdown_events', ['inverter_id'], unique=False)
    op.add_column('inverters', sa.Column('module_build_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('inverters_project_id_fkey'), 'inverters', type_='foreignkey')
    op.create_foreign_key(None, 'inverters', 'module_builds', ['module_build_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inverters', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inverters', type_='foreignkey')
    op.drop_constraint(None, 'inverters', type_='foreignkey')
    op.create_foreign_key(op.f('inverters_project_id_fkey'), 'inverters', 'projects', ['project_id'], ['id'])
    op.drop_column('inverters', 'module_build_id')
    op.drop_index(op.f('ix_breakdown_events_inverter_id'), table_name='breakdown_events')
    op.drop_index(op.f('ix_breakdown_events_id'), table_name='breakdown_events')
    op.drop_table('breakdown_events')
    op.drop_index(op.f('ix_monthly_kpis_project_id'), table_name='monthly_kpis')
    op.drop_index(op.f('ix_monthly_kpis_id'), table_name='monthly_kpis')
    op.drop_table('monthly_kpis')
    op.drop_index(op.f('ix_monthly_data_project_id'), table_name='monthly_data')
    op.drop_index(op.f('ix_monthly_data_id'), table_name='monthly_data')
    op.drop_table('monthly_data')
    op.drop_index(op.f('ix_module_builds_id'), table_name='module_builds')
    op.drop_table('module_builds')
    # ### end Alembic commands ###